
services:
  server:
    build:
      context: .
    ports:
      - 80:5001
    volumes:
      - ./app:/app
    # network_mode: "host"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

